import { Contact, Group } from '../types/contact';
import { upsertContact, upsertGroup } from '../db/database';
import { v4 as uuidv4 } from 'uuid';

const now = Math.floor(Date.now() / 1000);

const SEED_CONTACTS: Contact[] = [
  {
    id: 'seed-001',
    version: 1,
    fullName: 'Alice Johnson',
    firstName: 'Alice',
    lastName: 'Johnson',
    phones: [{ type: 'CELL', number: '+1 555 867 5309' }],
    emails: [{ type: 'WORK', address: 'alice@example.com' }],
    addresses: [{ type: 'HOME', street: '42 Maple Street', city: 'Edinburgh', state: 'Scotland', postcode: 'EH1 1AA', country: 'UK' }],
    organisation: 'Acme Corp',
    jobTitle: 'Lead Engineer',
    birthday: '1990-03-15',
    notes: 'Met at SiaConf 2024',
    photo: null,
    updatedAt: now,
    deleted: false,
    synced: true,
  },
  {
    id: 'seed-002',
    version: 1,
    fullName: 'Bob Martinez',
    firstName: 'Bob',
    lastName: 'Martinez',
    phones: [{ type: 'CELL', number: '+1 555 222 3456' }, { type: 'WORK', number: '+1 555 222 0001' }],
    emails: [{ type: 'PERSONAL', address: 'bob.martinez@gmail.com' }],
    addresses: [],
    organisation: 'Sia Foundation',
    jobTitle: 'Protocol Developer',
    birthday: '1988-07-22',
    notes: '',
    photo: null,
    updatedAt: now,
    deleted: false,
    synced: true,
  },
  {
    id: 'seed-003',
    version: 1,
    fullName: 'Carol Chen',
    firstName: 'Carol',
    lastName: 'Chen',
    phones: [{ type: 'CELL', number: '+1 555 333 7890' }],
    emails: [{ type: 'WORK', address: 'carol.chen@techcorp.io' }],
    addresses: [{ type: 'WORK', street: '88 Silicon Ave', city: 'San Francisco', state: 'CA', postcode: '94105', country: 'US' }],
    organisation: 'TechCorp',
    jobTitle: 'Product Manager',
    birthday: null,
    notes: 'Prefers Slack',
    photo: null,
    updatedAt: now,
    deleted: false,
    synced: false,
  },
  {
    id: 'seed-004',
    version: 1,
    fullName: 'David Kim',
    firstName: 'David',
    lastName: 'Kim',
    phones: [{ type: 'HOME', number: '+82 2 555 0042' }],
    emails: [{ type: 'PERSONAL', address: 'dkim@example.kr' }],
    addresses: [],
    organisation: '',
    jobTitle: '',
    birthday: '1995-12-01',
    notes: '',
    photo: null,
    updatedAt: now,
    deleted: false,
    synced: true,
  },
  {
    id: 'seed-005',
    version: 1,
    fullName: 'Emma Wilson',
    firstName: 'Emma',
    lastName: 'Wilson',
    phones: [{ type: 'CELL', number: '+44 7700 900123' }],
    emails: [{ type: 'WORK', address: 'emma@wilson.design' }],
    addresses: [{ type: 'HOME', street: '15 Garden Lane', city: 'London', state: 'England', postcode: 'SW1A 1AA', country: 'UK' }],
    organisation: 'Wilson Design Studio',
    jobTitle: 'UX Designer',
    birthday: '1992-06-08',
    notes: 'Brilliant designer, great taste',
    photo: null,
    updatedAt: now,
    deleted: false,
    synced: true,
  },
  {
    id: 'seed-006',
    version: 1,
    fullName: 'Frank Okonkwo',
    firstName: 'Frank',
    lastName: 'Okonkwo',
    phones: [{ type: 'CELL', number: '+234 803 555 0199' }],
    emails: [{ type: 'WORK', address: 'frank.ok@devops.ng' }],
    addresses: [],
    organisation: 'DevOps NG',
    jobTitle: 'DevOps Engineer',
    birthday: null,
    notes: '',
    photo: null,
    updatedAt: now,
    deleted: false,
    synced: false,
  },
  {
    id: 'seed-007',
    version: 1,
    fullName: 'Grace Park',
    firstName: 'Grace',
    lastName: 'Park',
    phones: [{ type: 'CELL', number: '+1 555 777 4444' }],
    emails: [{ type: 'PERSONAL', address: 'grace.park@mail.com' }, { type: 'WORK', address: 'gpark@university.edu' }],
    addresses: [],
    organisation: 'State University',
    jobTitle: 'Research Scientist',
    birthday: '1985-11-30',
    notes: 'CS PhD, distributed systems',
    photo: null,
    updatedAt: now,
    deleted: false,
    synced: true,
  },
  {
    id: 'seed-008',
    version: 1,
    fullName: 'Henry Thompson',
    firstName: 'Henry',
    lastName: 'Thompson',
    phones: [{ type: 'WORK', number: '+1 555 888 1234' }],
    emails: [{ type: 'WORK', address: 'hthompson@lawfirm.com' }],
    addresses: [{ type: 'WORK', street: '200 Broadway', city: 'New York', state: 'NY', postcode: '10007', country: 'US' }],
    organisation: 'Thompson & Associates',
    jobTitle: 'Attorney',
    birthday: null,
    notes: 'Specialises in tech IP',
    photo: null,
    updatedAt: now,
    deleted: false,
    synced: true,
  },
];

const SEED_GROUPS: Group[] = [
  {
    id: 'group-001',
    name: 'Sia Foundation',
    contactIds: ['seed-001', 'seed-002'],
    updatedAt: now,
    deleted: false,
    synced: true,
  },
  {
    id: 'group-002',
    name: 'Work',
    contactIds: ['seed-003', 'seed-005', 'seed-006', 'seed-007', 'seed-008'],
    updatedAt: now,
    deleted: false,
    synced: true,
  },
  {
    id: 'group-003',
    name: 'Friends',
    contactIds: ['seed-004', 'seed-001'],
    updatedAt: now,
    deleted: false,
    synced: false,
  },
];

export async function seedDemoData(): Promise<void> {
  for (const c of SEED_CONTACTS) await upsertContact(c);
  for (const g of SEED_GROUPS) await upsertGroup(g);
}
